name: CI Checks

on: 
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: CI Checks
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print TEST_KEY
        env:
          TEST_KEY: ${{ vars.TEST_KEY }}
        run: echo "$TEST_KEY"

      - name: Print TEST_VARIABLE_1
        run: echo ${{ vars.TEST_VARIABLE }}

      - name: Print TEST_VARIABLE_2
        env:
          TEST_VARIABLE: ${{ vars.TEST_VARIABLE }}
        run: echo "$TEST_VARIABLE"

      - name: Bump version
        uses: changesets/action@v1
        with:
          commit: "🔖 자동 버전 업데이트"
          title: "🔖 Changeset Version Bump"
          publish: false